from __future__ import annotations

import subprocess
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
SCRIPT = ROOT / "scripts" / "verify-dependency-policy.py"


def test_dependency_policy_script_passes_repo_policy() -> None:
    result = subprocess.run(
        ["python", str(SCRIPT), "--root", str(ROOT)],
        cwd=ROOT,
        check=False,
        capture_output=True,
        text=True,
    )
    assert result.returncode == 0, result.stdout + result.stderr


def test_dependency_policy_script_detects_pyproject_runtime_drift(tmp_path: Path) -> None:
    (tmp_path / "pyproject.toml").write_text(
        """
[project]
name = "tmp"
version = "0.0.1"
dependencies = ["click>=8.0"]
""".strip()
        + "\n",
        encoding="utf-8",
    )
    (tmp_path / "requirements.in").write_text("requests==2.32.3\n", encoding="utf-8")
    (tmp_path / "requirements.txt").write_text("-r requirements.in\n", encoding="utf-8")
    (tmp_path / "requirements-win.in").write_text("-r requirements.in\n", encoding="utf-8")
    (tmp_path / "requirements-win.txt").write_text("-r requirements.txt\n", encoding="utf-8")
    (tmp_path / "requirements-gpu.txt").write_text("-r requirements.txt\n", encoding="utf-8")
    (tmp_path / "requirements-lock.txt").write_text(
        "#\n# This file is autogenerated by pip-compile with Python 3.12\n# by the following command:\n#\n#    pip-compile --output-file=requirements-lock.txt requirements.in\n#\n",
        encoding="utf-8",
    )
    (tmp_path / "requirements-win-lock.txt").write_text(
        "#\n# This file is autogenerated by pip-compile with Python 3.12\n# by the following command:\n#\n#    pip-compile --output-file=requirements-win-lock.txt requirements-win.in\n#\n",
        encoding="utf-8",
    )

    result = subprocess.run(
        ["python", str(SCRIPT), "--root", str(tmp_path)],
        cwd=ROOT,
        check=False,
        capture_output=True,
        text=True,
    )
    assert result.returncode != 0
    assert "pyproject runtime dependency names missing from requirements.in" in (result.stdout + result.stderr)
