PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX prov: <http://www.w3.org/ns/prov#>

SELECT ?entity ?label ?description ?type ?sameAs ?attribute ?value
WHERE {
  VALUES ?entity { {{id}} }
  OPTIONAL { ?entity rdfs:label ?label }
  OPTIONAL { ?entity dcterms:description ?description }
  OPTIONAL { ?entity a ?type }
  OPTIONAL { ?entity owl:sameAs ?sameAs }
  OPTIONAL {
    ?entity ?attribute ?value .
    FILTER(?attribute NOT IN (rdf:type, rdfs:label, dcterms:description, owl:sameAs))
  }
}
ORDER BY ?entity ?attribute ?value
