PREFIX prov: <http://www.w3.org/ns/prov#>

SELECT ?source ?relation ?target ?timestamp
WHERE {
  VALUES ?source { {{id}} }
  {
    ?activity prov:used ?source .
    ?activity prov:generated ?target .
    BIND(prov:used AS ?relation)
    OPTIONAL { ?activity prov:endedAtTime ?timestamp }
  }
  UNION
  {
    ?source prov:wasDerivedFrom ?target .
    BIND(prov:wasDerivedFrom AS ?relation)
  }
}
ORDER BY ?relation ?target
