param(
    [string]$Timestamp = (Get-Date -Format 'yyyyMMdd-HHmm')
)

$branch = "auto/delta/$Timestamp"
& git checkout -b $branch
& git add monitor/*.json kg/delta/*.ttl kg/snapshots/*.srj tests/fixtures/cassettes/**/*.json CHANGELOG.md 2>$null
if ((git diff --cached --name-only).Count -eq 0) {
    Write-Host 'No changes detected.'
    exit 0
}
& git commit -m "chore(monitor): delta ingest $Timestamp"
$body = @"Autogenerated delta ingestion on $Timestamp."@
& gh pr create --title "chore: delta ingest $Timestamp" --body $body
