from __future__ import annotations

import argparse
import re
import sys
import tomllib
from pathlib import Path


def normalize_name(name: str) -> str:
    return re.sub(r"[-_.]+", "-", name.strip().lower())


def parse_requirement_name(spec: str) -> str | None:
    cleaned = spec.strip()
    if not cleaned or cleaned.startswith("#"):
        return None
    if cleaned.startswith(("-r", "--", "-c")):
        return None
    if cleaned.startswith(("git+", "http://", "https://", "file:", "svn+")):
        return None
    match = re.match(r"^\s*([A-Za-z0-9][A-Za-z0-9._-]*)", cleaned)
    if not match:
        return None
    return normalize_name(match.group(1))


def parse_requirement_file(path: Path) -> set[str]:
    names: set[str] = set()
    for raw in path.read_text(encoding="utf-8").splitlines():
        name = parse_requirement_name(raw)
        if name:
            names.add(name)
    return names


def parse_pyproject_dependencies(pyproject_path: Path) -> tuple[set[str], set[str]]:
    payload = tomllib.loads(pyproject_path.read_text(encoding="utf-8"))
    project = payload.get("project", {})
    runtime_specs = project.get("dependencies", [])
    gpu_specs = project.get("optional-dependencies", {}).get("gpu", [])

    runtime = set()
    for spec in runtime_specs:
        name = parse_requirement_name(str(spec))
        if name:
            runtime.add(name)

    gpu = set()
    for spec in gpu_specs:
        name = parse_requirement_name(str(spec))
        if name:
            gpu.add(name)

    return runtime, gpu


def read_non_comment_lines(path: Path) -> list[str]:
    lines = []
    for raw in path.read_text(encoding="utf-8").splitlines():
        stripped = raw.strip()
        if not stripped or stripped.startswith("#"):
            continue
        lines.append(stripped)
    return lines


def validate_wrapper(path: Path, expected_include: str) -> str | None:
    lines = read_non_comment_lines(path)
    expected = f"-r {expected_include}"
    if lines != [expected]:
        return (
            f"{path.name} must contain only '{expected}' as its non-comment content; "
            f"found: {lines if lines else '[]'}"
        )
    return None


def validate_lock_header(path: Path, source_name: str) -> str | None:
    header = "\n".join(path.read_text(encoding="utf-8").splitlines()[:8]).lower()
    if "autogenerated by pip-compile" not in header:
        return f"{path.name} is missing pip-compile autogenerated header."
    if source_name.lower() not in header:
        return f"{path.name} header does not reference {source_name}."
    return None


def run(root: Path) -> int:
    errors: list[str] = []

    pyproject = root / "pyproject.toml"
    req_in = root / "requirements.in"
    req_txt = root / "requirements.txt"
    req_win_in = root / "requirements-win.in"
    req_win_txt = root / "requirements-win.txt"
    req_gpu = root / "requirements-gpu.txt"
    req_lock = root / "requirements-lock.txt"
    req_win_lock = root / "requirements-win-lock.txt"
    req_dev = root / "requirements-dev.txt"

    required_files = [
        pyproject,
        req_in,
        req_txt,
        req_win_in,
        req_win_txt,
        req_gpu,
        req_lock,
        req_win_lock,
    ]
    missing = [p.name for p in required_files if not p.exists()]
    if missing:
        print("Dependency policy verification failed.")
        print("Missing required files:")
        for name in missing:
            print(f" - {name}")
        return 1

    runtime_pyproject, gpu_pyproject = parse_pyproject_dependencies(pyproject)
    req_in_names = parse_requirement_file(req_in)
    req_gpu_names = parse_requirement_file(req_gpu)

    missing_runtime = sorted(runtime_pyproject - req_in_names)
    if missing_runtime:
        errors.append(
            "pyproject runtime dependency names missing from requirements.in: "
            + ", ".join(missing_runtime)
        )

    missing_gpu = sorted(gpu_pyproject - req_gpu_names)
    if missing_gpu:
        errors.append(
            "pyproject optional gpu dependency names missing from requirements-gpu.txt: "
            + ", ".join(missing_gpu)
        )

    for path, expected in (
        (req_txt, "requirements.in"),
        (req_win_in, "requirements.in"),
        (req_win_txt, "requirements.txt"),
    ):
        wrapper_error = validate_wrapper(path, expected)
        if wrapper_error:
            errors.append(wrapper_error)

    for path, source in (
        (req_lock, "requirements.in"),
        (req_win_lock, "requirements-win.in"),
    ):
        lock_error = validate_lock_header(path, source)
        if lock_error:
            errors.append(lock_error)

    if req_dev.exists():
        errors.append(
            "requirements-dev.txt is not part of the supported dependency policy; "
            "use requirements.in plus lockfiles."
        )

    if errors:
        print("Dependency policy verification failed.")
        for error in errors:
            print(f" - {error}")
        return 1

    print("Dependency policy verification passed.")
    print("Authoritative input: requirements.in")
    print("Pinned resolution: requirements-lock.txt and requirements-win-lock.txt")
    print("Packaging metadata contract: pyproject.toml runtime deps must stay represented in requirements.in")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description="Verify dependency source-of-truth policy consistency.")
    parser.add_argument(
        "--root",
        default=".",
        help="Repository root path (defaults to current directory).",
    )
    args = parser.parse_args()
    root = Path(args.root).resolve()
    return run(root)


if __name__ == "__main__":
    raise SystemExit(main())
