PREFIX ear:  <https://ear.example.org/schema#>
PREFIX ent:  <https://ear.example.org/entity/>
PREFIX part: <https://ear.example.org/part/>
PREFIX dct:  <http://purl.org/dc/terms/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

DELETE { ent:__ID__ ear:name ?oldName . }
INSERT {
  ent:__ID__ a ear:Entity ;
             ear:name "__NAME__" ;
             ear:source "__SOURCE__" ;
             ear:programs "__PROGRAMS__" ;
             ear:country "__COUNTRY__" .
}
WHERE {
  OPTIONAL { ent:__ID__ ear:name ?oldName . }
}
